### PR TITLE
New upstream

### PR DESCRIPTION
**Pull request by sabourke**

### CODE REVIEW

**Comment by gijzelaerr** [comment]
i'm not sure if this is the right way to do it, it also requires tags, right? Which we can't do pull requests of.

**Comment by sabourke** [comment]
Ok, feel free to discard these. My thinking was that it makes sense to merge the "debian" directory into the "upstream" branch since that's the core of this repo but yeah, it makes more sense for "master" to keep its lineage.

**Comment by gijzelaerr** [comment]
all these repos are set up using the git buildpackage method:

http://honk.sigxcpu.org/projects/git-buildpackage/manual-html/gbp.html

upstream should contain the latest releast software without the debian folder.

**Comment by sabourke** [comment]
Right, the upstream pull request was just that (the latest releast software without the debian folder). But yeah, I guess I did the master update the wrong way around (branching upstream and pulling in debian/ from master). I'll redo and re-request.

**Pull request closed without merging**
